module2-task1 main page
htmlacademy-adaptive/1309327-sedona-25 pull request #2
Opened 2022-04-04 07:41 UTC by samanna27

2022-04-04 19:52 UTC, costigans requested changes

2022-04-04 19:52 UTC, costigans commented on source/index.html
> +        <button class="main-nav__burger" type="button"></button>
А где текст в кнопке?
Она не должна быть пустой

2022-04-04 19:52 UTC, costigans commented on source/index.html
> +            <li class="main-nav__item main-nav__item--active">
Активнвм может быть только один пункт меню.
Это та страниц, на которой мы сейчас находимся

2022-04-04 19:52 UTC, costigans commented on source/index.html
> +      <header class="cover-header">
Это не `header`, здесь излишне его использовать

2022-04-04 19:52 UTC, costigans commented on source/index.html
> +              <p class="advantage__number">— №1 —</p>
Давай используем нумерованный список? И эти элементы с порядковыми номерами мы стилизует как маркеры или псевдоэлементы

2022-04-04 19:53 UTC, costigans commented
Постучимь ко мне в Телеграм, или напиши свой

2022-04-05 04:14 UTC, samanna27 commented on source/index.html
> +        <button class="main-nav__burger" type="button"></button>
добавила текст - Бургер

2022-04-05 04:15 UTC, samanna27 commented on source/index.html
> +        <button class="main-nav__burger" type="button"></button>
кнопка

2022-04-05 04:15 UTC, samanna27 commented on source/index.html
> +            <li class="main-nav__item main-nav__item--active">
это на автомате скопировала )) убрала лишние

2022-04-05 04:16 UTC, samanna27 commented on source/index.html
> +      <header class="cover-header">
на div заменила

2022-04-05 04:17 UTC, samanna27 commented on source/index.html
> +              <p class="advantage__number">— №1 —</p>
сменила на ol. остается вопрос с тегом p в каждом элементе списка - нужен ли он тогда вообще?

2022-04-05 06:00 UTC, samanna27 commented on source/index.html
> +              <p class="advantage__number">— №1 —</p>
удалила теги <p> с нумерацией

2022-04-05 12:53 UTC, costigans requested changes
Валидатор [ругается](https://validator.w3.org/nu/?doc=https%3A%2F%2Fhtmlacademy-adaptive.github.io%2F1309327-sedona-25%2F2%2F)
А ещё, ты можешь [проверить БЭМ-дерево](https://yoksel.github.io/html-tree/)

2022-04-05 12:53 UTC, costigans commented on source/index.html
> +        <button class="main-nav__burger" type="button">Бургер кнопка</button>
Достаточно просто «Меню» :)

2022-04-09 09:50 UTC, samanna27 commented
"А ещё, ты можешь [проверить БЭМ-дерево](https://yoksel.github.io/html-tree/)" - вот это крутая штучка!

2022-04-09 09:53 UTC, samanna27 commented on source/index.html
> +        <button class="main-nav__burger" type="button">Бургер кнопка</button>
done

2022-04-11 07:28 UTC, merged