Module2 task2
htmlacademy-adaptive/1309327-sedona-25 pull request #4
Opened 2022-04-14 18:09 UTC by samanna27

2022-04-15 07:28 UTC, costigans requested changes
К этому заданию не относится стилизация, тебе следует удалить из этого PR (и ветки) всю папку со стилями.

2022-04-15 07:28 UTC, costigans commented on source/index.html
>            </span>
Удобнее будет заменить на векторные изображения

2022-04-15 07:28 UTC, costigans commented on source/index.html
> +              <div class="advantage__item--highlight">
Модификатор не может использоваться без блока/элемента который он модифицирует

2022-04-15 07:28 UTC, costigans commented on source/catalog.html
> +        <img class="cover__photo" src="img/back-mobile.jpg" alt="Фото-подложка">
А это точно контентное изображение?

2022-04-15 07:28 UTC, costigans commented on source/catalog.html
> +          <h1 class="catalog__offer-header">Заинтересовались?</h1>
На макете другой текст

2022-04-15 07:28 UTC, costigans commented on source/catalog.html
> +        <section class="catalog__offer">
На полноценный `section` не тянет

2022-04-15 07:28 UTC, costigans commented on source/form.html
> +          <label class="form-review__label form-review__label--optional" for="impression-choice3">Затрудняюсь ответить</label>
Для удобства стилизации можно обернуть в ненумерованный список

2022-04-19 13:26 UTC, samanna27 commented on source/catalog.html
> +        <img class="cover__photo" src="img/back-mobile.jpg" alt="Фото-подложка">
это фоновое изображение, можно его, конечно, через css в background поставить... Уберу тогда.

2022-04-19 13:30 UTC, samanna27 commented on source/catalog.html
> +        <section class="catalog__offer">
заменила на div

2022-04-19 13:32 UTC, samanna27 commented on source/catalog.html
> +          <h1 class="catalog__offer-header">Заинтересовались?</h1>
Досадно (( Исправила )

2022-04-19 13:41 UTC, samanna27 commented on source/form.html
> +          <label class="form-review__label form-review__label--optional" for="impression-choice3">Затрудняюсь ответить</label>
я radio обернула в список.

2022-04-19 13:53 UTC, samanna27 commented on source/index.html
>            </span>
пока не знаю ничего про векторные изображения, к своему стыду. Поэтому ничего по этому комментарию не правлю.

2022-04-19 13:54 UTC, samanna27 commented on source/index.html
> +              <div class="advantage__item--highlight">
исправила

2022-04-20 23:08 UTC, costigans requested changes

2022-04-20 23:08 UTC, costigans commented on package.json
> +    "lint": "npm run editorconfig",
Ой-ёй-ёй.
Это чего такое? Зачем?

2022-04-20 23:08 UTC, costigans commented on package.json
> +    "lint": "npm run editorconfig",
Если не проходят проверки — значит есть проблема в коде, удалять скрипт запуска стайллинта ненадо)

2022-04-21 06:31 UTC, merged